"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
require("./Home.css");
const Home = () => {
    return (react_1.default.createElement("div", { className: "home" },
        react_1.default.createElement("div", { className: "system-popover-non-drag" },
            react_1.default.createElement("div", { className: "popover-body" })),
        react_1.default.createElement("div", { className: "group-div1" },
            react_1.default.createElement("img", { className: "icon-iconslarm", alt: "", src: "/imgs/icon--iconslarm.svg" }),
            react_1.default.createElement("div", { className: "badge" },
                react_1.default.createElement("img", { className: "path-icon", alt: "", src: "/imgs/path.svg" }),
                react_1.default.createElement("div", { className: "div1" }, "3"))),
        react_1.default.createElement("div", { className: "hi-push-puttichai" }, "Hi, Push Puttichai"),
        react_1.default.createElement("img", { className: "oval-icon", alt: "", src: "/imgs/oval.svg" }),
        react_1.default.createElement("img", { className: "oval-icon", alt: "", src: "/imgs/avatar.svg" }),
        react_1.default.createElement("div", { className: "card-1" },
            react_1.default.createElement("div", { className: "rectangle5" }),
            react_1.default.createElement("div", { className: "account-and-card" },
                react_1.default.createElement("p", { className: "account" }, "Account"),
                react_1.default.createElement("p", { className: "account" }, "and Card")),
            react_1.default.createElement("img", { className: "icon-category-8", alt: "", src: "/imgs/icon--category--8.svg" })),
        react_1.default.createElement("div", { className: "card-1-copy-3" },
            react_1.default.createElement("div", { className: "rectangle5" }),
            react_1.default.createElement("div", { className: "account-and-card" }, "Mobile prepaid"),
            react_1.default.createElement("img", { className: "icon-category-81", alt: "", src: "/imgs/icon--category--81.svg" })),
        react_1.default.createElement("div", { className: "card-1-copy-6" },
            react_1.default.createElement("div", { className: "rectangle5" }),
            react_1.default.createElement("div", { className: "account-and-card" }, "Credit card"),
            react_1.default.createElement("img", { className: "icon-category-82", alt: "", src: "/imgs/icon--category--82.svg" })),
        react_1.default.createElement("div", { className: "card-1-copy" },
            react_1.default.createElement("div", { className: "rectangle5" }),
            react_1.default.createElement("div", { className: "account-and-card" }, "Transfer"),
            react_1.default.createElement("img", { className: "icon-category-8", alt: "", src: "/imgs/icon--category--83.svg" })),
        react_1.default.createElement("div", { className: "card-1-copy-4" },
            react_1.default.createElement("div", { className: "rectangle5" }),
            react_1.default.createElement("div", { className: "account-and-card" }, "Pay the bill"),
            react_1.default.createElement("img", { className: "icon-category-81", alt: "", src: "/imgs/icon--category--84.svg" })),
        react_1.default.createElement("div", { className: "card-1-copy-7" },
            react_1.default.createElement("div", { className: "rectangle5" }),
            react_1.default.createElement("div", { className: "account-and-card" }, "Transaction report"),
            react_1.default.createElement("img", { className: "icon-category-81", alt: "", src: "/imgs/icon--category--85.svg" })),
        react_1.default.createElement("div", { className: "card-1-copy-5" },
            react_1.default.createElement("div", { className: "rectangle5" }),
            react_1.default.createElement("div", { className: "account-and-card" }, "Save online"),
            react_1.default.createElement("img", { className: "icon-category-8", alt: "", src: "/imgs/icon--category--86.svg" })),
        react_1.default.createElement("div", { className: "card-1-copy-8" },
            react_1.default.createElement("div", { className: "rectangle5" }),
            react_1.default.createElement("div", { className: "account-and-card" }, "Beneficiary"),
            react_1.default.createElement("img", { className: "icon-category-81", alt: "", src: "/imgs/icon--category--87.svg" })),
        react_1.default.createElement("div", { className: "card-1-copy-2" },
            react_1.default.createElement("div", { className: "rectangle5" }),
            react_1.default.createElement("div", { className: "account-and-card" }, "Withdraw"),
            react_1.default.createElement("img", { className: "icon-category-8", alt: "", src: "/imgs/icon--category--88.svg" })),
        react_1.default.createElement("img", { className: "system-statusbars-white", alt: "", src: "/imgs/system--statusbars--white.svg" }),
        react_1.default.createElement("div", { className: "card-bank-multi" },
            react_1.default.createElement("div", { className: "rectangle14" }),
            react_1.default.createElement("div", { className: "rectangle15" }),
            react_1.default.createElement("img", { className: "group-icon1", alt: "", src: "/imgs/group.svg" }),
            react_1.default.createElement("div", { className: "john-smith" }, "John Smith"),
            react_1.default.createElement("div", { className: "amazon-platinium" }, "Amazon Platinium"),
            react_1.default.createElement("div", { className: "div2" }, "4756"),
            react_1.default.createElement("div", { className: "div3" }, "9018"),
            react_1.default.createElement("img", { className: "shape-icon", alt: "", src: "/imgs/shape.svg" }),
            react_1.default.createElement("img", { className: "shape-icon1", alt: "", src: "/imgs/shape1.svg" }),
            react_1.default.createElement("div", { className: "div4" }, "$3.469.52")),
        react_1.default.createElement("div", { className: "tab-bar-home" },
            react_1.default.createElement("div", { className: "rectangle16" }),
            react_1.default.createElement("img", { className: "icon-group-11", alt: "", src: "/imgs/icon--group-11.svg" }),
            react_1.default.createElement("img", { className: "icon-group-11-copy", alt: "", src: "/imgs/icon--group-11-copy.svg" }),
            react_1.default.createElement("img", { className: "icon-group-11-copy-2", alt: "", src: "/imgs/icon--group-11-copy-2.svg" }),
            react_1.default.createElement("div", { className: "rectangle17" }),
            react_1.default.createElement("div", { className: "home1" }, "Home"),
            react_1.default.createElement("img", { className: "path-icon1", alt: "", src: "/imgs/path1.svg" })),
        react_1.default.createElement("img", { className: "system-tabbar-display-down", alt: "", src: "/imgs/system--tabbar--display-down.svg" })));
};
exports.default = Home;
//# sourceMappingURL=Home.js.map